### PR TITLE
Overloads and cleanup

### PR DESCRIPTION
**Pull request by HRKings**
This PR adds some QoL changes. The full changelog:

- Overloads on all methods and callbacks, so if you pass an array it will know to return an array too (as proposed by #66)
- Cleanup the code, reduces nesting with less ifs, it also checks for an array and not an object
- Changes the tests to use overloads
- Update to the latest api-docs and made the necessary changes on the types generator to accomodate that
- Update dependencies
- Reject the promise on Getter error
- Bump version to 4.1.0
- Bump minimum node version to 14

Obs.: Sorry for being absent, I was very busy with personal life but I am back now!

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi @HRKings , thanks for the PR. Is it normal that it fails on all Nodes but the latest? I think we can drop support for 12, but not for 14

**Comment by HRKings** [comment]
Hey @Naramsim , I found the problem. Everything works as expected with node >= 12. The problem is one dev package required by the generators that is in an older version because of a vulnerability. I we upgrade the package everything works wonders. Keep in mind that the pokedex-promise itself still works and passes all tests even with this minor setback.

**Comment by Naramsim** [comment]
Yeah, I think as well we shouldn't support 12.

**Review by Naramsim — APPROVED** [review]

**Comment by Naramsim** [comment]
Maybe @HRKings you can update the GH workflows with the newer Node matrix. If the test pass, you can merge

**Comment by HRKings** [comment]
@Naramsim should I publish it ?

**Comment by Naramsim** [comment]
Yes, go for it :)

**Pull request merged**
